setup: &setup
  morphology: stem_enru
  charset_type: utf-8
  sql_range_step: 100000
  expand_keywords: 1
  min_prefix_len: 3
  enable_star: 1
  min_word_len: 3
  html_strip: 1
  use_64_bit: true

development:
  <<: *setup

production:
  <<: *setup
  port: 9310

test:
  <<: *setup
